name: reddit_app

networks:
  app-net:
    name: reddit-application

services:
  nginx:
    image: nginx:latest
    build: ./nginx
    networks:
      - app-net
    ports:
      - 80:80
    depends_on:
      - frontend

  frontend:
    image: frontend:latest
    build: ./frontend
    networks:
      - app-net
    environment:
      OAUTH2_CLIENT_ID_FILE: /run/secrets/client_id
      OAUTH2_CLIENT_SECRET_FILE: /run/secrets/client_secret
      ORIGIN: ${ORIGIN}
    secrets:
      - client_id
      - client_secret

  api:
    image: api:latest
    build: ./api
    networks:
      - app-net

  query:
    image: query:latest
    build: ./query
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_username
      - mongo_password
    depends_on:
      - mongo

  reddit:
    image: reddit:latest
    build: ./reddit
    networks:
      - app-net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    ports:
      - 27017:27017
    networks:
      - app-net
    secrets:
      - mongo_username
      - mongo_password

secrets:
  client_id:
    environment: OAUTH2_CLIENT_ID
  client_secret:
    environment: OAUTH2_CLIENT_SECRET
  mongo_username: 
    environment: MONGO_INITDB_ROOT_USERNAME
  mongo_password:
    environment: MONGO_INITDB_ROOT_PASSWORD

#     volumes:
#       - ./mongodb:/data/db

# # volumes:
# #   mongodb:
