name: reddit-app

services:

  certbot:
    image: reddit-app/certbot:latest
    build: ./certbot
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - 80:80
    networks:
      - app-net
    volumes:
      - ./letsencrypt:/etc/letsencrypt:rw # certs
      - /var/run/docker.sock:/var/run/docker.sock:ro # socket

  nginx:
    image: reddit-app/nginx:latest
    build: ./nginx
    networks:
      - app-net
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - 443:443
    depends_on:
      certbot:
        condition: service_healthy
      frontend:
        condition: service_started
    volumes:
      - ./letsencrypt:/etc/nginx/letsencrypt:ro # certs

  frontend:
    image: reddit-app/frontend:latest
    build: ./frontend
    networks:
      - app-net
    environment:
      OAUTH_CLIENT_ID_FILE: /run/secrets/client_id
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/client_secret
      AES_KEY_FILE: /run/secrets/aes_key
      AES_IV_FILE: /run/secrets/aes_iv
      ORIGIN: https://${DOMAIN}
    secrets:
      - client_id
      - client_secret
      - aes_key
      - aes_iv

  api:
    image: reddit-app/api:latest
    build: ./api
    networks:
      - app-net

  query:
    image: reddit-app/query:latest
    build: ./query
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_username
      - mongo_password
    depends_on:
      - mongo

  reddit:
    image: reddit-app/reddit:latest
    build: ./reddit
    networks:
      - app-net

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    networks:
      - app-net
    secrets:
      - mongo_username
      - mongo_password

networks:
  app-net:
    name: reddit-application

secrets:
  client_id:
    environment: OAUTH_CLIENT_ID
  client_secret:
    environment: OAUTH_CLIENT_SECRET
  mongo_username: 
    environment: MONGO_INITDB_ROOT_USERNAME
  mongo_password:
    environment: MONGO_INITDB_ROOT_PASSWORD
  aes_key:
    environment: AES_KEY
  aes_iv:
    environment: AES_IV

#     volumes:
#       - ./mongodb:/data/db

# # volumes:
# #   mongodb:
