name: reddit-saved-gallery

services:
  frontend:
    image: ${COMPOSE_PROJECT_NAME}/frontend
    container_name: frontend
    build: ./frontend
    networks:
      - app-net
    environment:
      OAUTH_CLIENT_ID_FILE: /run/secrets/client_id
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/client_secret
      AES_KEY_FILE: /run/secrets/aes_key
      AES_IV_FILE: /run/secrets/aes_iv
      ORIGIN: http://localhost:3000

      # optionally, pass in environment variables directly
      # OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      # OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      # AES_KEY: ${AES_KEY}
      # AES_IV: ${AES_IV}
    secrets:
      - client_id
      - client_secret
      - aes_key
      - aes_iv
    ports:
      - 3000:3000

  api:
    image: ${COMPOSE_PROJECT_NAME}/api
    container_name: api
    build: ./cmd/api
    networks:
      - app-net
    ports:
      - 4000:4000

  query:
    image: ${COMPOSE_PROJECT_NAME}/query
    container_name: query
    build: ./query # use the original Node.js service
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password

      # optionally, pass in environment variables directly
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    secrets:
      - mongo_username
      - mongo_password
    depends_on:
      - mongo

  reddit:
    image: ${COMPOSE_PROJECT_NAME}/reddit
    container_name: reddit
    build: ./cmd/reddit
    networks:
      - app-net

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    ports:
      - 27017:27017
    networks:
      - app-net
    secrets:
      - mongo_username
      - mongo_password

networks:
  app-net:
    name: ${COMPOSE_PROJECT_NAME}

secrets:
  client_id:
    environment: OAUTH_CLIENT_ID
  client_secret:
    environment: OAUTH_CLIENT_SECRET
  mongo_username: 
    environment: MONGO_INITDB_ROOT_USERNAME
  mongo_password:
    environment: MONGO_INITDB_ROOT_PASSWORD
  aes_key:
    environment: AES_KEY
  aes_iv:
    environment: AES_IV
