name: reddit-saved-gallery

services:
  api:
    image: ${COMPOSE_PROJECT_NAME}/api
    container_name: api
    build: ./cmd/api
    networks:
      - app-net
    ports:
      - 4000:4000

  query:
    image: ${COMPOSE_PROJECT_NAME}/query
    container_name: query
    build: ./query # use the original Node.js service
    networks:
      - app-net
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_username
      - mongo_password
    depends_on:
      - mongo

  reddit:
    image: ${COMPOSE_PROJECT_NAME}/reddit
    container_name: reddit
    build: ./cmd/reddit
    networks:
      - app-net

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    ports:
      - 27017:27017
    networks:
      - app-net
    secrets:
      - mongo_username
      - mongo_password

networks:
  app-net:
    name: reddit-application

secrets:
  client_id:
    environment: OAUTH_CLIENT_ID
  client_secret:
    environment: OAUTH_CLIENT_SECRET
  mongo_username: 
    environment: MONGO_INITDB_ROOT_USERNAME
  mongo_password:
    environment: MONGO_INITDB_ROOT_PASSWORD