version: "3.9"

networks:
  app-net:
    name: reddit-application

services:
  # client:
  #   image: client:latest
  #   build: ./client
  #   networks:
  #     - app-net
  #   ports:
  #     - 3000:3000

  api:
    image: api:latest
    build: ./api
    networks:
      - app-net
    ports:
      - 4000:4000

  query:
    image: query:latest
    build: ./query
    networks:
      - app-net
    ports:
      - 4001:4001

  reddit:
    image: reddit:latest
    build: ./reddit
    networks:
      - app-net
    ports:
      - 4002:4002

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-net
    ports:
      - 27017:27017

#     volumes:
#       - ./mongodb:/data/db

# # volumes:
# #   mongodb:
