@CLIENT_ID = 7RjOp92rHTjjgXK5fNJ46A
@CLIENT_SECRET = 22G7pGtn87B69pXW8H6U3X2o6GTBZw
@CALLBACK = http://localhost:5173/callback
@CODE = TeFAmRoilKmbjUt6uOGKGneAAUaPEg

# go to URL to get authorization code
https://www.reddit.com/api/v1/authorize?client_id={{CLIENT_ID}}&response_type=code&state=12345&redirect_uri={{CALLBACK}}&duration=permanent&scope=*
https://www.reddit.com/api/v1/authorize?client_id=7RjOp92rHTjjgXK5fNJ46A&response_type=code&state=12345&redirect_uri=http://localhost:5173/callback&duration=permanent&scope=*
###
POST https://www.reddit.com/api/v1/access_token HTTP/1.1
Authorization: Basic {{CLIENT_ID}}:{{CLIENT_SECRET}}
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code={{CODE}}&redirect_uri={{CALLBACK}}
###
@JWT = eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzE0NTA0MzkzLjMwMDgwOCwiaWF0IjoxNzE0NDE3OTkzLjMwMDgwNywianRpIjoiRVNsQ2NTV1BwcGE4SlYtMXlKQ1Job0FLOVl6SjNnIiwiY2lkIjoiN1JqT3A5MnJIVGpqZ1hLNWZOSjQ2QSIsImxpZCI6InQyXzcwNWc4aTBpIiwiYWlkIjoidDJfNzA1ZzhpMGkiLCJsY2EiOjE1OTI3Nzc1NTU3NDMsInNjcCI6ImVKeUtWdEpTaWdVRUFBRF9fd056QVNjIiwicmNpZCI6ImJBbEVzMW1HbzkyMnNwZFhJNTJHRWVJVzl5NXVnano4NjgzUU1sUFBERGMiLCJmbG8iOjh9.YU998vNxRtJE8lZSXVByf9Er2kdPuKeLYQETzYNInqDG3Hlbl2VkzdFdKNC7O_zS5zZy-UfXrwpbWWU089F-ZBnSzO8M-dnMrBb701itZAKyEZnp3dUv_iiC8vceZJi9hq83gnn2itWWTV8uxKHp-A_Fj9-gQvo9vZ4Mwz-qvbnFrhjh21Xsbe-eJpZEByEV3i9jJS5sx3aI0Quzotcbwm2eC6XWU1y5kDINEswIbOb2QBZ8AjQs05xObUlAs2Q0Be0HXBa4s1hTtNeZnDlyftRD1PL6oQv_D_jLDWST_qh81lE7IJ2TVXPc0WLepbMheRFgGkDV3Hp44csnMtRM_w
###
GET https://oauth.reddit.com/user/1234353/saved?limit=100&raw_json=1 HTTP/1.1
Authorization: bearer {{JWT}}