@CLIENT_ID = 7RjOp92rHTjjgXK5fNJ46A
@CLIENT_SECRET = 22G7pGtn87B69pXW8H6U3X2o6GTBZw
@CALLBACK = http://localhost:5173/callback
@CODE = G2amRrXVX1GKxGS-dZqnLwDUdxhvCg

# go to URL to get authorization code
https://www.reddit.com/api/v1/authorize?client_id={{CLIENT_ID}}&response_type=code&state=12345&redirect_uri={{CALLBACK}}&duration=permanent&scope=*
https://www.reddit.com/api/v1/authorize?client_id=7RjOp92rHTjjgXK5fNJ46A&response_type=code&state=12345&redirect_uri=http://localhost:5173/callback&duration=permanent&scope=*
###
POST https://www.reddit.com/api/v1/access_token HTTP/1.1
Authorization: Basic {{CLIENT_ID}}:{{CLIENT_SECRET}}
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code={{CODE}}&redirect_uri={{CALLBACK}}
###
@JWT = eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzE0Mzc4Nzg1LjI4NTY4OSwiaWF0IjoxNzE0MjkyMzg1LjI4NTY4OSwianRpIjoiX0RJb0hzcFJMU1gteHpBbmpOTHJvZmZpd3hGdlF3IiwiY2lkIjoiN1JqT3A5MnJIVGpqZ1hLNWZOSjQ2QSIsImxpZCI6InQyXzcwNWc4aTBpIiwiYWlkIjoidDJfNzA1ZzhpMGkiLCJsY2EiOjE1OTI3Nzc1NTU3NDMsInNjcCI6ImVKeUtWdEpTaWdVRUFBRF9fd056QVNjIiwicmNpZCI6IjdfeTJXWDM0VUVnZUk2WE8xMUJ5R2hacE5ZbDJwRHpFY1lpY19FdU1sM0kiLCJmbG8iOjh9.HlADgQvDPLGDN3PEaRQrDw74JlidrU-s_AcVLEcSc6bLjpqavU2xVgH_fv8MHJgfx9GImcfN-OlBIQZ4jBYQd3umqkFi-gmh8K08wC0agSvm9x_AKfcjS6vSNje81S40GPw5ZQbfz5GRoARpAutD11H62leUdw6oy_je3AAP2OjeFgiq7y7A61TivIQK7wNOdhGo7VD588yMWfQBesk7-ACAdDfYXsBEMZNqQCJLPAayGh7vWoFa-SprhxFXmPLQ3eLsSwMwpS1LbSxqHzdHb44Adb2SWl6ZKRXZ2uV5AnXqcmObg01SW_ra6aGRHws98D9GS9bzOH2vxX6_ALlKVg
###
GET https://oauth.reddit.com/user/1234353/saved?limit=100&raw_json=1 HTTP/1.1
Authorization: bearer {{JWT}}