name: ci
run-name: ${{ github.actor }} is running ci

on: 
  push:
  workflow_dispatch:

env:
  REPO_NAME: reddit-saved-gallery

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Expose GitHub runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Run tests
        run: make test
      - name: Build Go binaries
        run: make build
      - name: Build Docker images
        run: docker compose build
      - name: Save names of all built Docker images to an environment variable
        run: |
          TEMP_VAR=$(docker images --format "{{.Repository}}:{{.Tag}}" |
            grep -E "$REPO_NAME" |
            tr '\n' ' ')
          echo "DOCKER_IMAGES=$TEMP_VAR" >> "$GITHUB_ENV"
      - name: Tar and gzip Docker images
        run: |
          echo "$DOCKER_IMAGES"
          docker save $DOCKER_IMAGES |
          gzip >
          images.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: images.tar.gz
          path: ./images.tar.gz
          retention-days: 1
  
  deliver-to-ghcr:
    # only run on push to main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-and-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: images.tar.gz
      - name: Decompress and load Docker images from artifact
        run: docker load -i images.tar.gz
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker images to ghcr
        run: docker compose push
