name: deploy
run-name: ${{ github.actor }} is deploying to production

on:
  workflow_dispatch:

env:
  REPO_NAME: reddit-saved-gallery

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://savedgallery.net
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Copy files to remote machine
        run: |
          echo "${{ secrets.ENV_FILE }}" > ./.env
          chmod 600 ./.env
          scp -i ~/.ssh/key.pem ./.env ${{ secrets.USER }}@${{ secrets.HOSTNAME }}:~/${{ env.REPO_NAME }}
          scp -i ~/.ssh/key.pem ./compose.yaml ${{ secrets.USER }}@${{ secrets.HOSTNAME }}:~/${{ env.REPO_NAME }}
      - name: SSH to remote machine and run docker compose up
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.USER }}@${{ secrets.HOSTNAME }} 'cd ~/${{ env.REPO_NAME }} && sudo docker compose down && sudo docker compose pull && sudo docker compose up -d'
